pipeline {
    agent {
        docker {
            image 'node:6-alpine'
        }
    }
    environment { 
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install --registry https://registry.npm.taobao.org'
                sh 'npm run release'
            }
        }
        stage('Test') {
            steps {
                echo 'test...........................'
            }
        }
        stage('Deliver') { 
            steps {
               echo 'deliver'
            }
        }
        stabe(deploy){
            steps {
                echo "deploy"
            }
        }
    }
}
